### ISSUE TITLE
Error in laravel 5.8

### ISSUE THREAD

**Issue by IgorDePaula** [gordonzero/monolog-telegram#1]
"Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 237"
--
exception | "Telegram\\Bot\\Exceptions\\TelegramResponseException"

"/home/igor/projetos/CRM/vendor/irazasyed/telegram-bot-sdk/src/Exceptions/TelegramResponseException.php"

**Comment by IgorDePaula** [comment]
local.ERROR: Call to undefined function Monolog\Handler\curl_init()

**Comment by gordonzero** [comment]
I've been seeing that too actually ... i think it's an invalid character that telegram doesn't like ... not 100% sure. i'll do some testing on it tomorrow though.

**Comment by gordonzero** [comment]
also @IgorDePaula just to verify you have actually gotten it to send you messages before this error correct

**Comment by IgorDePaula** [comment]
Yes, I verified. Was a big message sent to telegram. I modified to a less message and works.

**Comment by gordonzero** [comment]
did notice a couple of minor things going though my code including a hard coded App Name in the message string. Gonna patch that and push out a new version here soon.
